import '../components/nav-F1.js'
import '../components/piloto-card.js'
import '../components/equipo-card.js'
import '../components/circuito-card.js'
import '../components/vehiculo-card.js'
import '../components/piloto-detail.js'